import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";

export default function Document() {
  return (
    <Html lang="en" className="overscroll-none">
      <Head>
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="AiDolls" />
        <meta property="og:title" content="AiDolls" />
        <meta
          property="og:description"
          content="Millions of girls generated by A.i."
        />
        <meta property="og:url" content="https://aidolls.org" />
        <meta property="og:locale" content="en_US" />
        <meta property="og:image" content="https://aidolls.org/preview.jpg" />
        <meta
          property="og:image:secure_url"
          content="https://aidolls.org/preview.jpg"
        />
        <div className="container">
          <Script
            src="https://www.googletagmanager.com/gtag/js?id=G-VWC01FW6XV"
            strategy="afterInteractive"
          />
          <Script id="google-analytics" strategy="afterInteractive">
            {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-VWC01FW6XV');
        `}
          </Script>
        </div>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
