import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="w-80 text-center">
        <br />
        <br />
        <br />
        <span className="text-5xl">Hello,</span>
        <br />
        <br />
        <span className="text-xl">Do you like pretty girls?</span>
        <br />
        <span className="text-xl">I bet you do...</span>
        <br />
      </div>
      <Link className="text-xl" href={`viewer`}>
        Here we go...
      </Link>

      <div className="text-xs text-center w-80">
        all photos are generated by a.i. in realtime
        <br />
        <br />
        if you have any questions.
        <br />
        contact us at <a href="mailto:shawhu@gmail.com">shawhu@gmail.com</a>
      </div>
    </main>
  );
}
