import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

import { listS3Bucket } from "../lib/S3ImagePreloader";

export async function getServerSideProps() {
  const s3data: { key: string; size: number }[] = await listS3Bucket();
  const s3urlprefix: string = `https://ai-tokyo-001.s3.ap-northeast-1.amazonaws.com/`;
  return {
    props: { s3data, s3urlprefix }, // will be passed to the page component as props
  };
}

export default function Home({ s3data, s3urlprefix }: any) {
  //console.log(JSON.stringify(s3data));
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <Head>
        <title>AiPhoto</title>
      </Head>
      <div className="bg-stone-400 absolute top-0 left-0 w-full h-full -z-50 grid gap-0 grid-rows-10 grid-cols-12">
        {s3data.map((img: { key: string; size: number }) => (
          <Image
            className="blur-[2px]"
            loader={({ src, width, quality }) => {
              return s3urlprefix + img.key;
            }}
            alt={img.key}
            key={img.key}
            src={img.key}
            width={20}
            height={40}
          />
        ))}
      </div>
      <div className="bg-stone-900/50 absolute top-0 left-0 w-full h-full -z-49"></div>
      <div className="w-80 text-center z-20">
        <br />
        <br />
        <br />
        <span className="text-5xl text-white  z-20">Hello,</span>
        <br />
        <br />
        <span className="text-xl text-white  z-20">
          Do you like pretty girls?
        </span>
        <br />
        <span className="text-xl text-white  z-20">I bet you do...</span>
      </div>
      <Link className="text-3xl text-white z-20" href={`viewer`}>
        Sign up now
      </Link>
      <br />
      <div className="text-xs text-center w-80 text-white  z-20">
        all photos are generated by a.i. in realtime
        <br />
        <br />
        if you have any questions.
        <br />
        contact us at <a href="mailto:shawhu@gmail.com">shawhu@gmail.com</a>
      </div>
    </main>
  );
}
